#!/bin/bash
# Wrapper for patch-hda.pl for users who like to click on scripts 
# from the finder
#
# Copyright (c) 2012-2013 B.C. <bcc24x7@gmail.com> (bcc9 at insanelymac.com). 
# All rights reserved.

IFS=
cd `dirname $0`
exec ./patch-hda.pl
